apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: peanut
    namespace: peanut
spec:
    interval: 15m
    chart:
        spec:
            chart: peanut
            version: 2.0.11
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: peanut
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        ingress:
            main:
                enabled: false
        release_name: peanut
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 10688
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                NUT_HOST: localhost
                                NUT_PORT: 3493
                                PASSWORD: ""
                                USERNAME: ""
                                WEB_PORT: '{{ .Values.service.main.ports.main.port }}'
                replicas: 1
                type: Deployment
