apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: calibre-web
    namespace: calibre-web
spec:
    interval: 15m
    chart:
        spec:
            chart: calibre-web
            version: 20.3.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: calibre-web
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: "${S3ID}"
                bucket: "${S3PREFIX}"
                encrKey: "${S3ENCR}"
                name: backblaze
                path: ""
                secretKey: "${S3KEY}"
                type: s3
                url: "${S3url}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: "calibre-web.${DOMAIN_0}"
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Media
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            customkv:
                                - key: username
                                  value: "${CALIBRE_WEB_USERNAME}"
                                - key: password
                                  value: "${CALIBRE_WEB_PW}"
                            enabled: true
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: ipwhitelist
                              namespace: ""
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: calibre-web
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 8083
                        protocol: http
                        targetPort: 8083
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            probes:
                                liveness:
                                    path: /
                                    type: http
                                readiness:
                                    path: /
                                    type: http
                                startup:
                                    path: /
                                    type: http
                replicas: 1
                type: Deployment
