apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: flaresolverr
    namespace: flaresolverr
spec:
    interval: 15m
    chart:
        spec:
            chart: flaresolverr
            version: 14.0.10
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: flaresolverr
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: "${S3ID}"
                bucket: "${S3PREFIX}"
                encrKey: "${S3ENCR}"
                name: backblaze
                path: ""
                secretKey: "${S3KEY}"
                type: s3
                url: "${S3url}"
        ingress:
            main:
                enabled: false
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: flaresolverr
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 8191
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                BROWSER_TIMEOUT: 40000
                                CAPTCHA_SOLVER: none
                                HEADLESS: true
                                HOST: 0.0.0.0
                                LOG_HTML: false
                                LOG_LEVEL: info
                                PORT: '{{ .Values.service.main.ports.main.port }}'
                                TEST_URL: https://www.google.com
                replicas: 1
                type: Deployment
