apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: terraria-tshock
    namespace: terraria-tshock
spec:
    interval: 15m
    chart:
        spec:
            chart: terraria-tshock
            version: 8.3.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: terraria-tshock
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        ingress:
            main:
                enabled: false
        persistence:
            serverfiles:
                enabled: true
                mountPath: /serverdata/serverfiles
                readOnly: false
                storageClass: ""
        release_name: terraria-tshock
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 9014
                        protocol: http
                        targetPort: 8080
                type: LoadBalancer
            tcp:
                enabled: true
                loadBalancerIP: ""
                ports:
                    tcp:
                        enabled: true
                        port: 7777
                type: LoadBalancer
        terraria:
            autocreate: "1"
            easy_game_params:
                noupnp: true
                secure: false
                steam: false
            lang: en-US
            maxplayers: 16
            motd: "${TERRARIA_MOTD}"
            pass: "${TERRARIA_PW}"
            seed: "${TERRARIA_SEED}"
            worldname: "${TERARIA_WORLD_NAME}"
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            envFrom:
                                - secretRef:
                                    name: terraria-secret
                replicas: 1
                type: Deployment
