apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6YeJFmtz9GL/nwZs1VyBx1LR0521pL3X0UwJfvwHApnSRwc1vc7BSxU8ukG+/9ygfI/hU1hRhU/fzp5EgbGprKcNEflLWFiyQ5i2oAU/PRLYwNifyAcjtT0lyunsP+yM0HRAurudUs3cRQIE5CB/vuo4CfgODGKIfY4NkOInmXlcdTgyEWPp5O/kZ3rDMWg6+uDgKqSzSUEIgYYL0eCnBgYT+JVfeCTKU4X1N2cX3IOOrRo+JqwvMJs65kGhX37xDY1exoiOt+6AGFbc98xVN4K+HIUstFUqGnTjU5iyhkrv899mrwHuLnvFwlOl0F6Zd9u/+YXWkDaEe31iyuciw8MS9tLBBA/Y8v82VMmIbEXfMMI9JmaDESABQF81NCt1,iv:3VxveJLd6hTR7zo4e+TC51jlMb1oZLCTf8qVowxXVyI=,tag:Ie4r3t4zNvOuk1b3iTQz4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:XyvGIvYhZKYMd03PMcA/E7WLn+/CAyPuA6e9CQ3oynDxRNyV5o6SepJWx02ws9jzGlt765YaFE/eMAPglruFXPkSlCvmtCFWAWiRDO5WXq5e0VDzLAss66G5AkIb1mxf5ppbCKznTmKH+MhojUYFpF5jMRNmzmNKU5wQ45qPk0HVd1KUbFKHlCwR04IJjVV7PdKcon1TcXHqWKKxNlPCTyDOjcAphwfcF8O/ttoiEP4uaSWw24cO5H79f9Av1Dap6u7hDLOmAMIVm/FS9w==,iv:J0l4TKIpmv/hzTwbCvdoN+I58gpUSFT17CyXR7rUOQE=,tag:Nyos/rPesi0ko9J91O/ZXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:7KP4CnKfJEhuhu4OPMXctlnUUhJYjkd1+jNFmGIPC7Pi4WXrwlg+/ySfhfH/Flc/RGdbmOChdrGg0FDJdbBqTttFLZog7HD4RNEMUTRhxmBDDRy0GUJdVjxfO8BjYgcZ3qhANOL0Vzad0z7T/xpYN7lqP2y/lNKGPPBVbgsIOOUEyIH5+UBAdIU77triNGq3YagITl3Fzjc/acfiwQ4fWFGe2ULvsH/cVBM1,iv:XX6qWCr1dypbCRBpbPjc3SmjXd+2dDwCdY25KhH93vA=,tag:7ZaTlxo/se8ilskIw4pauQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ue2daxzmd40mlqsjw7sdpyue92akx4rz9u00fcewrzrp6727cs5sqqcguu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVzlEcUtlQi9lRGdyc1hI
            MXNXNldvMFl1TktmaVVkQ1VuK2xpWWpuaUZnCkZkNDVqWEFZdzlobEhyVVByZ0FR
            b2hQUEFHUTlUaTF2OVk4RHJlclFRUjgKLS0tIExnbHpxZzRxNkEzcVdFMk9BQUY2
            UXRqbWlkSEh4Umk0WmJycDdQWnprZ2MKzj1iFHCHGDKMG66hHW7xaLQSripiiA+m
            O7KMitgvlBlSA2oXlqSoiQEIXYDz3A9UzZavs1JjcSYMFpPu7Z6D9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T19:14:24Z"
    mac: ENC[AES256_GCM,data:MekYJwn+xo/W1Qy2zbKdPNqnLcgFvntTpn9zCJihAWaumdvoF4dsYBE6gITRzwmwvtiTDP2ffOGUWbZ2Sfj9WogyGNyueG/1xjAK4UKAH7/TJRr1akJ5iNgFy7fHjg+orFC+SuYS1S2brAhXyI1ozK+T3FOwaYdM8dcXccyzKnU=,iv:iEnwgQOx6kSwllQGP6ToW+XR+pGgev3hGgrsq2v8ZbE=,tag:+iYEhmphwXt9JYQIUBozUQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
