apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: navidrome
    namespace: navidrome
spec:
    interval: 15m
    chart:
        spec:
            chart: navidrome
            version: 20.1.5
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: navidrome
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: "${S3ID}"
                bucket: "${S3PREFIX}"
                encrKey: "${S3ENCR}"
                name: backblaze
                path: ""
                secretKey: "${S3KEY}"
                type: s3
                url: "${S3url}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: "navidrome.${DOMAIN_0}"
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Media
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            data:
                enabled: true
                mountPath: /data
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
            music:
                enabled: true
                mountPath: /music
                readOnly: false
                storageClass: ""
        release_name: navidrome
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 4533
                        targetPort: 4533
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                ND_ENABLETRANSCODINGCONFIG: false
                                ND_LOGLEVEL: info
                                ND_MUSICFOLDER: /music
                                ND_SCANSCHEDULE: '@every 15m'
                                ND_SESSIONTIMEOUT: 24h
                replicas: 1
                type: Deployment
