apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cloudflareddns
    namespace: cloudflareddns
spec:
    interval: 15m
    chart:
        spec:
            chart: cloudflareddns
            version: 11.3.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: cloudflareddns
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        cloudflareddns:
            api_key: ""
            api_token: "${DOMAIN_0_CLOUDFLARE_TOKEN}"
            api_token_zone: ""
            detect_mode: dig-whoami.cloudflare
            detect_override: ""
            host_zone_record:
                - domain: "${DOMAIN_0}"
                  record: A
                  zone: bef7f8cf840ef46949ec0296245a91db
            interval: 300
            log_level: 3
            user: "${DOMAIN_0_EMAIL}"
        credentials:
            backblaze:
                accessKey: "${S3ID}"
                bucket: "${S3PREFIX}"
                encrKey: "${S3ENCR}"
                name: backblaze
                path: ""
                secretKey: "${S3KEY}"
                type: s3
                url: "${S3url}"
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: cloudflareddns
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsNonRoot: false
                runAsUser: 0
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: false
                ports:
                    main:
                        enabled: false
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            envFrom:
                                - secretRef:
                                    name: secret
                            probes:
                                liveness:
                                    enabled: false
                                readiness:
                                    enabled: false
                                startup:
                                    enabled: false
                replicas: 1
                type: Deployment
