apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: tachidesk-docker
    namespace: tachidesk-docker
spec:
    interval: 15m
    chart:
        spec:
            chart: tachidesk-docker
            version: 8.4.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: tachidesk-docker
    values:
        TZ: "${TZ}"
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            backblaze:
                accessKey: "${S3ID}"
                bucket: "${S3PREFIX}"
                encrKey: "${S3ENCR}"
                name: backblaze
                path: ""
                secretKey: "${S3KEY}"
                type: s3
                url: "${S3url}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: "tachidesk.${DOMAIN_0}"
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: domain
                        enabled: true
                    homepage:
                        description: ""
                        enabled: true
                        group: Media
                        icon: ""
                        name: ""
                        widget:
                            custom:
                                key: ""
                            enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: ipwhitelist
                              namespace: ""
        persistence:
            appdata:
                enabled: true
                mountPath: /home/suwayomi/.local/share/Tachidesk
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: backblaze
                      dest:
                        enabled: false
                      name: config
                      src:
                        enabled: true
                      type: restic
            library:
                autoPermissions:
                    enabled: false
                enabled: true
                mountPath: /home/suwayomi/.local/share/Tachidesk/downloads
                path: /mnt/EXOS-Cache/manga
                readOnly: false
                server: 192.168.1.55
                type: nfs
            local-library:
                enabled: true
                mountPath: /home/suwayomi/.local/share/Tachidesk/local
                readOnly: false
                storageClass: ""
        release_name: tachidesk-docker
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 4567
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                AUTO_DOWNLOAD_AHEAD_LIMIT: 0
                                AUTO_DOWNLOAD_CHAPTERS: false
                                AUTO_DOWNLOAD_EXCLUDE_UNREAD: true
                                BACKUP_INTERVAL: 1
                                BACKUP_TTL: 1
                                BASIC_AUTH_ENABLED: false
                                BASIC_AUTH_PASSWORD: ""
                                BASIC_AUTH_USERNAME: ""
                                BIND_IP: 0.0.0.0
                                BIND_PORT: '{{ .Values.service.main.ports.main.port }}'
                                DEBUG: false
                                DOWNLOAD_AS_CBZ: true
                                EXTENSION_REPOS: '[ "https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json" ]'
                                FLARESOLVERR_ENABLED: false
                                FLARESOLVERR_SESSION_NAME: suwayomi
                                FLARESOLVERR_SESSION_TTL: 15
                                FLARESOLVERR_TIMEOUT: 60
                                FLARESOLVERR_URL: ""
                                GQL_DEBUG: false
                                MAX_SOURCES_IN_PARALLEL: 6
                                SOCKS_PROXY_ENABLED: false
                                SOCKS_PROXY_HOST: ""
                                SOCKS_PROXY_PORT: ""
                                UPDATE_EXCLUDE_COMPLETED: true
                                UPDATE_EXCLUDE_STARTED: true
                                UPDATE_EXCLUDE_UNREAD: true
                                UPDATE_INTERVAL: 12
                                UPDATE_MANGA_INFO: false
                                WEB_UI_CHANNEL: stable
                                WEB_UI_ENABLED: true
                                WEB_UI_FLAVOR: WebUI
                                WEB_UI_UPDATE_INTERVAL: 23
                replicas: 1
                type: Deployment
