apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kubernetes-reflector
    namespace: kubernetes-reflector
spec:
    interval: 15m
    chart:
        spec:
            chart: kubernetes-reflector
            version: 5.0.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: kubernetes-reflector
    values:
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        kubernetesReflector:
            logLevel: Information
        operator:
            register: true
        rbac:
            main:
                clusterWide: true
                enabled: true
                primary: true
                rules:
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                        - secrets
                      verbs:
                        - get
                        - list
                        - watch
                        - create
                        - update
                        - patch
                        - delete
                    - apiGroups:
                        - ""
                      resources:
                        - namespaces
                      verbs:
                        - watch
                        - list
        release_name: kubernetes-reflector
        resources: {}
        service:
            main:
                enabled: false
        serviceAccount:
            main:
                enabled: true
                primary: true
        workload:
            main:
                podSpec:
                    automountServiceAccountToken: true
                    containers:
                        main:
                            env:
                                ES_Reflector__Kubernetes__SkipTlsVerify: "false"
                                ES_Reflector__Watcher__Timeout: ""
                                ES_Serilog__MinimumLevel__Default: '{{ .Values.kubernetesReflector.logLevel }}'
                            probes:
                                liveness:
                                    path: /healthz
                                    port: 25080
                                    type: http
                                readiness:
                                    path: /healthz
                                    port: 25080
                                    type: http
                                startup:
                                    path: /healthz
                                    port: 25080
                                    type: http
                            securityContext:
                                readOnlyRootFilesystem: true
                                runAsNonRoot: true
                replicas: 1
                type: Deployment
